-   id: check-untracked-migrations
    name: Untracked Django migrations checker
    description: "Forbid untracked Django migrations"
    entry: check-untracked-migrations
    language: python
    types: [python]
    pass_filenames: false
    require_serial: true
-   id: check-unapplied-migrations
    name: Check unapplied migrations with manage.py makemigrations --check
    entry: python manage.py makemigrations --check
    language: system
    types: [python]
    pass_filenames: false
    require_serial: true
-   id: po-location-format
    name: Changes location format for .po files
    entry: po-location-format
    language: python
    files: \.po$
